In [2]:
import numpy as np
import pandas as pd

In [35]:
anno = pd.read_csv('annotation.csv')

In [36]:
anno['filename'] = [f'sp_{i}.jpg'for i in range(1, 56)]

In [37]:
anno

     filename reading
0    sp_1.jpg     NaN
1    sp_2.jpg     NaN
2    sp_3.jpg     NaN
3    sp_4.jpg     NaN
4    sp_5.jpg     NaN
5    sp_6.jpg     NaN
6    sp_7.jpg     NaN
7    sp_8.jpg     NaN
8    sp_9.jpg     NaN
9   sp_10.jpg     NaN
10  sp_11.jpg     NaN
11  sp_12.jpg     NaN
12  sp_13.jpg     NaN
13  sp_14.jpg     NaN
14  sp_15.jpg     NaN
15  sp_16.jpg     NaN
16  sp_17.jpg     NaN
17  sp_18.jpg     NaN
18  sp_19.jpg     NaN
19  sp_20.jpg     NaN
20  sp_21.jpg     NaN
21  sp_22.jpg     NaN
22  sp_23.jpg     NaN
23  sp_24.jpg     NaN
24  sp_25.jpg     NaN
25  sp_26.jpg     NaN
26  sp_27.jpg     NaN
27  sp_28.jpg     NaN
28  sp_29.jpg     NaN
29  sp_30.jpg     NaN
30  sp_31.jpg     NaN
31  sp_32.jpg     NaN
32  sp_33.jpg     NaN
33  sp_34.jpg     NaN
34  sp_35.jpg     NaN
35  sp_36.jpg     NaN
36  sp_37.jpg     NaN
37  sp_38.jpg     NaN
38  sp_39.jpg     NaN
39  sp_40.jpg     NaN
40  sp_41.jpg     NaN
41  sp_42.jpg     NaN
42  sp_43.jpg     NaN
43  sp_44.jpg     NaN
44  sp_45.jpg     NaN
45  sp_46.jpg     NaN
46  sp_47.jpg     NaN
47  sp_48.jpg     NaN
48  sp_49.jpg     NaN
49  sp_50.jpg     NaN
50  sp_51.jpg     NaN
51  sp_52.jpg     NaN
52  sp_53.jpg     NaN
53  sp_54.jpg     NaN
54  sp_55.jpg     NaN

In [38]:
anno.to_csv('annotation.csv')

In [39]:
term_names = []
for i, name in enumerate(anno['filename']):
    term = str(name).replace('sp_', '')
    if len(term) == 5:
        term_names.append('sp_00'+term)
    elif len(term) == 6:
        term_names.append('sp_0'+term)
    elif len(term) == 7:
        term_names.append('sp_'+term)
print(term_names)

['sp_001.jpg', 'sp_002.jpg', 'sp_003.jpg', 'sp_004.jpg', 'sp_005.jpg', 'sp_006.jpg', 'sp_007.jpg', 'sp_008.jpg', 'sp_009.jpg', 'sp_010.jpg', 'sp_011.jpg', 'sp_012.jpg', 'sp_013.jpg', 'sp_014.jpg', 'sp_015.jpg', 'sp_016.jpg', 'sp_017.jpg', 'sp_018.jpg', 'sp_019.jpg', 'sp_020.jpg', 'sp_021.jpg', 'sp_022.jpg', 'sp_023.jpg', 'sp_024.jpg', 'sp_025.jpg', 'sp_026.jpg', 'sp_027.jpg', 'sp_028.jpg', 'sp_029.jpg', 'sp_030.jpg', 'sp_031.jpg', 'sp_032.jpg', 'sp_033.jpg', 'sp_034.jpg', 'sp_035.jpg', 'sp_036.jpg', 'sp_037.jpg', 'sp_038.jpg', 'sp_039.jpg', 'sp_040.jpg', 'sp_041.jpg', 'sp_042.jpg', 'sp_043.jpg', 'sp_044.jpg', 'sp_045.jpg', 'sp_046.jpg', 'sp_047.jpg', 'sp_048.jpg', 'sp_049.jpg', 'sp_050.jpg', 'sp_051.jpg', 'sp_052.jpg', 'sp_053.jpg', 'sp_054.jpg', 'sp_055.jpg']

In [40]:
anno['filename'] = term_names

In [41]:
anno

      filename reading
0   sp_001.jpg     NaN
1   sp_002.jpg     NaN
2   sp_003.jpg     NaN
3   sp_004.jpg     NaN
4   sp_005.jpg     NaN
5   sp_006.jpg     NaN
6   sp_007.jpg     NaN
7   sp_008.jpg     NaN
8   sp_009.jpg     NaN
9   sp_010.jpg     NaN
10  sp_011.jpg     NaN
11  sp_012.jpg     NaN
12  sp_013.jpg     NaN
13  sp_014.jpg     NaN
14  sp_015.jpg     NaN
15  sp_016.jpg     NaN
16  sp_017.jpg     NaN
17  sp_018.jpg     NaN
18  sp_019.jpg     NaN
19  sp_020.jpg     NaN
20  sp_021.jpg     NaN
21  sp_022.jpg     NaN
22  sp_023.jpg     NaN
23  sp_024.jpg     NaN
24  sp_025.jpg     NaN
25  sp_026.jpg     NaN
26  sp_027.jpg     NaN
27  sp_028.jpg     NaN
28  sp_029.jpg     NaN
29  sp_030.jpg     NaN
30  sp_031.jpg     NaN
31  sp_032.jpg     NaN
32  sp_033.jpg     NaN
33  sp_034.jpg     NaN
34  sp_035.jpg     NaN
35  sp_036.jpg     NaN
36  sp_037.jpg     NaN
37  sp_038.jpg     NaN
38  sp_039.jpg     NaN
39  sp_040.jpg     NaN
40  sp_041.jpg     NaN
41  sp_042.jpg     NaN
42  sp_043.jpg     NaN
43  sp_044.jpg     NaN
44  sp_045.jpg     NaN
45  sp_046.jpg     NaN
46  sp_047.jpg     NaN
47  sp_048.jpg     NaN
48  sp_049.jpg     NaN
49  sp_050.jpg     NaN
50  sp_051.jpg     NaN
51  sp_052.jpg     NaN
52  sp_053.jpg     NaN
53  sp_054.jpg     NaN
54  sp_055.jpg     NaN

In [42]:
anno.to_csv('annotation.csv', index=False)